function getSubtitle(){
    const messages = [
        'the duckening',
        'frogs',
        'i forgor 💀',
        'space pirates',
        'E',
        'object Object',
        '|  ||  ||  | --',
        'a̵̧̧̛̦̳̠͙̟̗̺͍͎̼͍͈͓̤̝͛̅̄̈̓́͘͠͝a̶̖̻̬̲̭̯̺̫̪̠̱̞͂̔̆̊̓͘͝ͅạ̷̡͚͕̤͙̜̜̔̓́͑͛͛̃̕ä̷̢̛̜̤̖̞̗̰͓̣͔̜͉́͌á̷̡̨̰͕̟̟͎͙̠̖̬̮́̐̌̈́̃̅̈́̉͒̏́̇͊̚͝͝ͅa̵͔̗̭͕̮̩͇̺͈̤̍̃̔͐̽͆̏̇̽̀͘̚̚̕͠͠ͅa̸̢̛͔͉̭͓̬͖̼̺̟͔͉͛̄̈̈̑̈́͋̀̆̐̉̇̀͌̇͠a̷̡͙̘̜͈̥̬̫̺̿̔͘ͅa̵̢̧͍̺̩̻͔̳͕̞̗͙͓̮͌̎̍̀̀̊̍̿̂̈́̃́͆͌̄̚̕͜a̴̞͉̺̤̍̓͒͗̽̐͒̐͜͠',
        'can probably run in Internet Explorer',
        'blood for the Blood God',
        'quack for your life',
        'greetings traveller',
        'i made this instead of studying for an exam',
        'consider sleeping',
        'smol duck',
        'no regrets',
        'highly illegal',
        'use DuckDuckGo',
        'just ducking around',
        'nerd',
        'clicking "More duck" will help you cope with reality',
        'do not turn around',
        'beep boop',
        'doug doug',
        'hello {SUBJECT_NAME}',
        '<3',
        'yeah',
        'the fog is coming',
        'the enemy of the world',
        'previous message was a lie',
        'INSERT DUCK PUN HERE',
        'unspeakable horrors',
        'mildly radioactive',
        'clean your Downloads folder',
        'if not friend, why friend shaped?',
        'OUCH',
        'some rubber ducks have forward facing eyes, implying that they are predators',
        'IDDQD'
        ];
    const randomIndex = Math.round(Math.random()*messages.length);
    document.getElementById("subtitle").innerHTML = messages[randomIndex];
}
